# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\Build.ui'
#
# Created: Tue May 27 22:32:43 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WidgetBuild(object):
    def setupUi(self, WidgetBuild):
        WidgetBuild.setObjectName(_fromUtf8("WidgetBuild"))
        WidgetBuild.resize(773, 535)
        self.verticalLayout_2 = QtGui.QVBoxLayout(WidgetBuild)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labelCharPicture = QtGui.QLabel(WidgetBuild)
        self.labelCharPicture.setMinimumSize(QtCore.QSize(300, 200))
        self.labelCharPicture.setMaximumSize(QtCore.QSize(300, 200))
        self.labelCharPicture.setFrameShape(QtGui.QFrame.StyledPanel)
        self.labelCharPicture.setFrameShadow(QtGui.QFrame.Raised)
        self.labelCharPicture.setText(_fromUtf8(""))
        self.labelCharPicture.setScaledContents(True)
        self.labelCharPicture.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCharPicture.setObjectName(_fromUtf8("labelCharPicture"))
        self.horizontalLayout.addWidget(self.labelCharPicture)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelName = QtGui.QLabel(WidgetBuild)
        self.labelName.setObjectName(_fromUtf8("labelName"))
        self.gridLayout_2.addWidget(self.labelName, 0, 0, 1, 1)
        self.labelSubclass = QtGui.QLabel(WidgetBuild)
        self.labelSubclass.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelSubclass.setObjectName(_fromUtf8("labelSubclass"))
        self.gridLayout_2.addWidget(self.labelSubclass, 1, 2, 1, 1)
        self.lineEditSubclass = QtGui.QLineEdit(WidgetBuild)
        self.lineEditSubclass.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSubclass.sizePolicy().hasHeightForWidth())
        self.lineEditSubclass.setSizePolicy(sizePolicy)
        self.lineEditSubclass.setMinimumSize(QtCore.QSize(130, 0))
        self.lineEditSubclass.setMaximumSize(QtCore.QSize(130, 16777215))
        self.lineEditSubclass.setText(_fromUtf8(""))
        self.lineEditSubclass.setReadOnly(True)
        self.lineEditSubclass.setObjectName(_fromUtf8("lineEditSubclass"))
        self.gridLayout_2.addWidget(self.lineEditSubclass, 1, 3, 1, 1)
        self.labelLevel = QtGui.QLabel(WidgetBuild)
        self.labelLevel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelLevel.setObjectName(_fromUtf8("labelLevel"))
        self.gridLayout_2.addWidget(self.labelLevel, 1, 0, 1, 1)
        self.spinBoxLevel = QtGui.QSpinBox(WidgetBuild)
        self.spinBoxLevel.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBoxLevel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxLevel.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.spinBoxLevel.setMinimum(1)
        self.spinBoxLevel.setMaximum(70)
        self.spinBoxLevel.setProperty("value", 70)
        self.spinBoxLevel.setObjectName(_fromUtf8("spinBoxLevel"))
        self.gridLayout_2.addWidget(self.spinBoxLevel, 1, 1, 1, 1)
        self.lineEditClass = QtGui.QLineEdit(WidgetBuild)
        self.lineEditClass.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditClass.sizePolicy().hasHeightForWidth())
        self.lineEditClass.setSizePolicy(sizePolicy)
        self.lineEditClass.setMinimumSize(QtCore.QSize(130, 0))
        self.lineEditClass.setMaximumSize(QtCore.QSize(130, 16777215))
        self.lineEditClass.setReadOnly(True)
        self.lineEditClass.setObjectName(_fromUtf8("lineEditClass"))
        self.gridLayout_2.addWidget(self.lineEditClass, 0, 3, 1, 1)
        self.labelClass = QtGui.QLabel(WidgetBuild)
        self.labelClass.setObjectName(_fromUtf8("labelClass"))
        self.gridLayout_2.addWidget(self.labelClass, 0, 2, 1, 1)
        self.lineEditName = QtGui.QLineEdit(WidgetBuild)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditName.sizePolicy().hasHeightForWidth())
        self.lineEditName.setSizePolicy(sizePolicy)
        self.lineEditName.setMinimumSize(QtCore.QSize(90, 0))
        self.lineEditName.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEditName.setText(_fromUtf8(""))
        self.lineEditName.setObjectName(_fromUtf8("lineEditName"))
        self.gridLayout_2.addWidget(self.lineEditName, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelTPEqual = QtGui.QLabel(WidgetBuild)
        self.labelTPEqual.setObjectName(_fromUtf8("labelTPEqual"))
        self.gridLayout.addWidget(self.labelTPEqual, 2, 4, 1, 1)
        self.labelQPTotal = QtGui.QLabel(WidgetBuild)
        self.labelQPTotal.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.labelQPTotal.setObjectName(_fromUtf8("labelQPTotal"))
        self.gridLayout.addWidget(self.labelQPTotal, 1, 0, 1, 1)
        self.labelSPTotal = QtGui.QLabel(WidgetBuild)
        self.labelSPTotal.setObjectName(_fromUtf8("labelSPTotal"))
        self.gridLayout.addWidget(self.labelSPTotal, 0, 0, 1, 1)
        self.labelSPMinus = QtGui.QLabel(WidgetBuild)
        self.labelSPMinus.setObjectName(_fromUtf8("labelSPMinus"))
        self.gridLayout.addWidget(self.labelSPMinus, 0, 2, 1, 1)
        self.labelQPMinus = QtGui.QLabel(WidgetBuild)
        self.labelQPMinus.setObjectName(_fromUtf8("labelQPMinus"))
        self.gridLayout.addWidget(self.labelQPMinus, 1, 2, 1, 1)
        self.labelTPTotal = QtGui.QLabel(WidgetBuild)
        self.labelTPTotal.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.labelTPTotal.setObjectName(_fromUtf8("labelTPTotal"))
        self.gridLayout.addWidget(self.labelTPTotal, 2, 0, 1, 1)
        self.labelQPEqual = QtGui.QLabel(WidgetBuild)
        self.labelQPEqual.setObjectName(_fromUtf8("labelQPEqual"))
        self.gridLayout.addWidget(self.labelQPEqual, 1, 4, 1, 1)
        self.labelTPMinus = QtGui.QLabel(WidgetBuild)
        self.labelTPMinus.setObjectName(_fromUtf8("labelTPMinus"))
        self.gridLayout.addWidget(self.labelTPMinus, 2, 2, 1, 1)
        self.labelSPEqual = QtGui.QLabel(WidgetBuild)
        self.labelSPEqual.setObjectName(_fromUtf8("labelSPEqual"))
        self.gridLayout.addWidget(self.labelSPEqual, 0, 4, 1, 1)
        self.spinBoxSpTotal = QtGui.QSpinBox(WidgetBuild)
        self.spinBoxSpTotal.setMinimumSize(QtCore.QSize(90, 0))
        self.spinBoxSpTotal.setMaximumSize(QtCore.QSize(90, 16777215))
        self.spinBoxSpTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxSpTotal.setReadOnly(True)
        self.spinBoxSpTotal.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxSpTotal.setMaximum(99999)
        self.spinBoxSpTotal.setProperty("value", 0)
        self.spinBoxSpTotal.setObjectName(_fromUtf8("spinBoxSpTotal"))
        self.gridLayout.addWidget(self.spinBoxSpTotal, 0, 1, 1, 1)
        self.spinBoxQpTotal = QtGui.QSpinBox(WidgetBuild)
        self.spinBoxQpTotal.setMinimumSize(QtCore.QSize(90, 0))
        self.spinBoxQpTotal.setMaximumSize(QtCore.QSize(90, 16777215))
        self.spinBoxQpTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxQpTotal.setReadOnly(True)
        self.spinBoxQpTotal.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxQpTotal.setMaximum(99999)
        self.spinBoxQpTotal.setProperty("value", 0)
        self.spinBoxQpTotal.setObjectName(_fromUtf8("spinBoxQpTotal"))
        self.gridLayout.addWidget(self.spinBoxQpTotal, 1, 1, 1, 1)
        self.spinBoxTpTotal = QtGui.QSpinBox(WidgetBuild)
        self.spinBoxTpTotal.setMinimumSize(QtCore.QSize(90, 0))
        self.spinBoxTpTotal.setMaximumSize(QtCore.QSize(90, 16777215))
        self.spinBoxTpTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTpTotal.setReadOnly(True)
        self.spinBoxTpTotal.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxTpTotal.setMaximum(99999)
        self.spinBoxTpTotal.setProperty("value", 0)
        self.spinBoxTpTotal.setObjectName(_fromUtf8("spinBoxTpTotal"))
        self.gridLayout.addWidget(self.spinBoxTpTotal, 2, 1, 1, 1)
        self.spinBoxSpUsed = QtGui.QSpinBox(WidgetBuild)
        self.spinBoxSpUsed.setMinimumSize(QtCore.QSize(90, 0))
        self.spinBoxSpUsed.setMaximumSize(QtCore.QSize(90, 16777215))
        self.spinBoxSpUsed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxSpUsed.setReadOnly(True)
        self.spinBoxSpUsed.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxSpUsed.setMaximum(99999)
        self.spinBoxSpUsed.setProperty("value", 0)
        self.spinBoxSpUsed.setObjectName(_fromUtf8("spinBoxSpUsed"))
        self.gridLayout.addWidget(self.spinBoxSpUsed, 0, 3, 1, 1)
        self.spinBoxQpUsed = QtGui.QSpinBox(WidgetBuild)
        self.spinBoxQpUsed.setMinimumSize(QtCore.QSize(90, 0))
        self.spinBoxQpUsed.setMaximumSize(QtCore.QSize(90, 16777215))
        self.spinBoxQpUsed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxQpUsed.setReadOnly(True)
        self.spinBoxQpUsed.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxQpUsed.setMaximum(99999)
        self.spinBoxQpUsed.setProperty("value", 0)
        self.spinBoxQpUsed.setObjectName(_fromUtf8("spinBoxQpUsed"))
        self.gridLayout.addWidget(self.spinBoxQpUsed, 1, 3, 1, 1)
        self.spinBoxTpUsed = QtGui.QSpinBox(WidgetBuild)
        self.spinBoxTpUsed.setMinimumSize(QtCore.QSize(90, 0))
        self.spinBoxTpUsed.setMaximumSize(QtCore.QSize(90, 16777215))
        self.spinBoxTpUsed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTpUsed.setReadOnly(True)
        self.spinBoxTpUsed.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxTpUsed.setMaximum(99999)
        self.spinBoxTpUsed.setProperty("value", 0)
        self.spinBoxTpUsed.setObjectName(_fromUtf8("spinBoxTpUsed"))
        self.gridLayout.addWidget(self.spinBoxTpUsed, 2, 3, 1, 1)
        self.spinBoxSpRemaining = QtGui.QSpinBox(WidgetBuild)
        self.spinBoxSpRemaining.setMinimumSize(QtCore.QSize(90, 0))
        self.spinBoxSpRemaining.setMaximumSize(QtCore.QSize(90, 16777215))
        self.spinBoxSpRemaining.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxSpRemaining.setReadOnly(True)
        self.spinBoxSpRemaining.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxSpRemaining.setMaximum(99999)
        self.spinBoxSpRemaining.setProperty("value", 0)
        self.spinBoxSpRemaining.setObjectName(_fromUtf8("spinBoxSpRemaining"))
        self.gridLayout.addWidget(self.spinBoxSpRemaining, 0, 5, 1, 1)
        self.spinBoxQpRemaining = QtGui.QSpinBox(WidgetBuild)
        self.spinBoxQpRemaining.setMinimumSize(QtCore.QSize(90, 0))
        self.spinBoxQpRemaining.setMaximumSize(QtCore.QSize(90, 16777215))
        self.spinBoxQpRemaining.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxQpRemaining.setReadOnly(True)
        self.spinBoxQpRemaining.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxQpRemaining.setMaximum(99999)
        self.spinBoxQpRemaining.setProperty("value", 0)
        self.spinBoxQpRemaining.setObjectName(_fromUtf8("spinBoxQpRemaining"))
        self.gridLayout.addWidget(self.spinBoxQpRemaining, 1, 5, 1, 1)
        self.spinBoxTpRemaining = QtGui.QSpinBox(WidgetBuild)
        self.spinBoxTpRemaining.setMinimumSize(QtCore.QSize(90, 0))
        self.spinBoxTpRemaining.setMaximumSize(QtCore.QSize(90, 16777215))
        self.spinBoxTpRemaining.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTpRemaining.setReadOnly(True)
        self.spinBoxTpRemaining.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxTpRemaining.setMaximum(99999)
        self.spinBoxTpRemaining.setProperty("value", 0)
        self.spinBoxTpRemaining.setObjectName(_fromUtf8("spinBoxTpRemaining"))
        self.gridLayout.addWidget(self.spinBoxTpRemaining, 2, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget = QtGui.QTabWidget(WidgetBuild)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSP = QtGui.QWidget()
        self.tabSP.setObjectName(_fromUtf8("tabSP"))
        self.tabWidget.addTab(self.tabSP, _fromUtf8(""))
        self.tabSkillTree = QtGui.QWidget()
        self.tabSkillTree.setObjectName(_fromUtf8("tabSkillTree"))
        self.tabWidget.addTab(self.tabSkillTree, _fromUtf8(""))
        self.tabQP = QtGui.QWidget()
        self.tabQP.setObjectName(_fromUtf8("tabQP"))
        self.tabWidget.addTab(self.tabQP, _fromUtf8(""))
        self.tabTP = QtGui.QWidget()
        self.tabTP.setObjectName(_fromUtf8("tabTP"))
        self.tabWidget.addTab(self.tabTP, _fromUtf8(""))
        self.tabQuests = QtGui.QWidget()
        self.tabQuests.setObjectName(_fromUtf8("tabQuests"))
        self.tabWidget.addTab(self.tabQuests, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(WidgetBuild)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WidgetBuild)

    def retranslateUi(self, WidgetBuild):
        WidgetBuild.setWindowTitle(_translate("WidgetBuild", "Build", None))
        self.labelName.setText(_translate("WidgetBuild", "Name:", None))
        self.labelSubclass.setText(_translate("WidgetBuild", "Subclass:", None))
        self.labelLevel.setText(_translate("WidgetBuild", "Level:", None))
        self.labelClass.setText(_translate("WidgetBuild", "Class:", None))
        self.labelTPEqual.setText(_translate("WidgetBuild", "=", None))
        self.labelQPTotal.setText(_translate("WidgetBuild", "QP:", None))
        self.labelSPTotal.setText(_translate("WidgetBuild", "SP:", None))
        self.labelSPMinus.setText(_translate("WidgetBuild", "-", None))
        self.labelQPMinus.setText(_translate("WidgetBuild", "-", None))
        self.labelTPTotal.setText(_translate("WidgetBuild", "TP:", None))
        self.labelQPEqual.setText(_translate("WidgetBuild", "=", None))
        self.labelTPMinus.setText(_translate("WidgetBuild", "-", None))
        self.labelSPEqual.setText(_translate("WidgetBuild", "=", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSP), _translate("WidgetBuild", "SP-Skills", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSkillTree), _translate("WidgetBuild", "SkillTree", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabQP), _translate("WidgetBuild", "QP-Skills", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTP), _translate("WidgetBuild", "TP-Skills", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabQuests), _translate("WidgetBuild", "Quests", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    WidgetBuild = QtGui.QWidget()
    ui = Ui_WidgetBuild()
    ui.setupUi(WidgetBuild)
    WidgetBuild.show()
    sys.exit(app.exec_())

